Add pencil icon to edit property name
PaulBredl/config-assistant pull request #365
Opened 2023-10-05 16:50 UTC by beyond2void

2023-10-05 16:51 UTC, beyond2void commented
still one thing in progress: avoid it navigating inside

2023-10-06 12:09 UTC, PaulBredl commented on frontend/config-assistant/src/components/gui-editor/PropertyMetadata.vue
> +  const id: string = getId();
For these three lines and "element.focus" there exists focusUtils, which you could use I think

2023-10-07 09:11 UTC, PaulBredl approved these changes

2023-10-07 09:13 UTC, PaulBredl requested changes
Still todo: clicking on the property name should zoom into it

2023-10-09 17:16 UTC, PaulBredl requested changes
When I add a new (additional) property, the name of the property is no longer selected and I can no longer enter anything

2023-10-11 12:08 UTC, PaulBredl approved these changes

2023-10-11 12:08 UTC, Logende approved these changes

2023-10-11 12:08 UTC, merged